config/routes.rb
Rails.application.routes.draw do
  resources :authors
  devise_for :users
  root 'pages#home' 
  get 'book/:id/delete',to: "books#destroy"
  resources :books
  resources :users

  namespace :api do 
    namespace :v1 do 
      resources :books
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/author.rb
class Author < ApplicationRecord
    has_many :books
end

app/models/book.rb
class Book < ApplicationRecord
    validates_uniqueness_of :id
    validates :judul, uniqueness: { case_sensitive: false, message: " sudah ada, cari yang lain!!" }
    belongs_to :author

    validates :judul, presence: true
    validates :tahun_terbit, presence: true
    validates :author_id, presence: true
    validates :email, format: { with: /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i, message: 'is not a valid email address' }
end

app/models/user.rb
class User < ApplicationRecord
  enum role: [:regular, :admin, :user]
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  # devise :database_authenticatable, :registerable,
  #        :recoverable, :rememberable, :validatable
  
  devise :database_authenticatable,
         :recoverable, :rememberable, :validatable
  
  validates :username, presence: true
  
  validates :email, presence: true, uniqueness: true
  validates :email, format: { with: /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i, message: 'is not a valid email address' }
end

app/controllers/api/v1/books_controller.rb
class Api::V1::BooksController < ApplicationController 
    def index
        per_page = params[:per_page] || 5
        page = params[:page] || 1 # Default 
        @books = Book.includes(:author).page(page).per(per_page)
        render json: @books, include: :author
      end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    layout :set_layout

    private 

    def set_layout 
        # if current_user && current_usr.admin == true
        # Ensures you won't error if not logged in when you check if admin
        if current_user&.admin? || current_user&.regular?
            'admin'
        else
            "frontend"
        end
    end
end

app/controllers/authors_controller.rb
class AuthorsController < ApplicationController

  before_action :set_author, only: [:edit, :update, :show, :destory]

  def index
    @authors = Author.page(params[:page]).per(5).order("created_at DESC")
  end
  def show     
  end
  def new     
  end
  def create 
    @author = Author.new(author_params)
    # render plain: @book.inspect
    if @author.save 
      flash[:notice] = "Book was created successfully"
      redirect_to new_book_path
    else
      render 'new'
    end
  end
  def edit 

  end

  private 

  def set_author
    @book = Author.find(params[:id])
  end
  
  def author_params
    params.require(:author).permit(:name)
  end
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  before_action :set_book, only: [:edit, :update, :show, :destroy]
  def index
    @books = Book.page(params[:page]).per(5).order("created_at DESC")
  end

  def show    
  end
  def new   
     @book = Book.new
  end

  def create 
    @book = Book.new(book_params)
    # render plain: @book.inspect
    if @book.save 
      HelloJob.perform_later(@book)
      flash[:notice] = "Book was created successfully"
      redirect_to books_path
    else
      render 'new'
    end
  end
  def edit 

  end
  def update
    if @book.update(book_params)
      flash[:notice] = "Book was updated successfully."
      redirect_to books_path
    else
      render 'edit'
    end
  end

  def destroy
    # if @book.present?
    #     @book.destroy
    # end
    Book.destroy(params[:id])
    flash[:notice] = "Book was deleted"
    redirect_to books_path
  end
  

  private 

  def set_book 
    @book = Book.find(params[:id])
  end
  
  def book_params
    params.require(:book).permit(:judul, :tahun_terbit,:email, :author_id)
  end
end

app/controllers/frontend_controller.rb
class FrontendController < ActionController::Base
    # layout :set_layout

    # private 

    # def set_layout 
    #     # if current_user && current_usr.admin == true
    #     # Ensures you won't error if not logged in when you check if admin
    #     if current_user&.admin? || current_user&.regular?
    #         'admin'
    #     else
    #         'frontend'
    #     end
    # end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
    def index
        @users = User.page(params[:page]).per(5).order("created_at DESC")
    end
    def new   
        @user = User.new
    end
     def create 
        @user = User.new(user_params)
        # render plain: @book.inspect
        if @user.save 
        #   HelloJob.perform_later(@user)
          flash[:notice] = "User was created successfully"
          redirect_to users_path
        else
          render 'new'
        end
      end

      private       
      
      def user_params
        # Dapatkan semua parameter yang diperlukan
        permitted_params = params.require(:user).permit(:email, :username, :password)      
        # Tambahkan nilai default untuk :role jika tidak ada atau kosong
        permitted_params[:role] ||= 'admin'
      
        return permitted_params
      end
      
end

app/helpers/application_helper.rb
module ApplicationHelper
    def resource_name
        :user
      end
    
      def resource
        @resource ||= User.new
      end
    
      def devise_mapping
        @devise_mapping ||= Devise.mappings[:user]
      end
end

app/helpers/author_helper.rb
module AuthorHelper
end

app/helpers/book_helper.rb
module BookHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/user_helper.rb
module UserHelper
end

app/views/authors/index.html.erb
<div class="card">
    <div class="card-header">
    <h3 class="card-title">List Authors</h3>
    </div>
    <!-- /.card-header -->
    <div class="card-body">
    <table class="table table-bordered">
        <thead>
        <tr>
            <th style="width: 10px">No</th>
            <th>Name</th>  
        </tr>
        </thead>
        <tbody>
      <% @authors.each_with_index do |author, index| %>
        <tr>
            <td><%= index + 1 %> </td>
            <td><%= author.name %> </td>  
        </tr>        
    <% end %>
        </tbody>
    </table>
    </div>
    <!-- /.card-body -->
    <div class="card-footer clearfix">
    <ul class="pagination pagination-sm m-0 float-right">
        <%= paginate @authors %>      
    </ul>
    </div>
</div>
<!-- /.card -->

app/views/base/_control_sidebar.html.erb
 <!-- Control Sidebar -->
  <aside class="control-sidebar control-sidebar-dark">
    <!-- Control sidebar content goes here -->
    <div class="p-3">
      <h5>Title</h5>
      <p>Sidebar content</p>
    </div>
  </aside>
  <!-- /.control-sidebar -->

app/views/base/_footer.html.erb
 <!-- Main Footer -->
  <footer class="main-footer">
    <!-- To the right -->
    <div class="float-right d-none d-sm-inline">
      Anything you want
    </div>
    <!-- Default to the left -->
    <strong>Technical Test Ruby on Rails &copy; 18 October 2023 <a href="https://google.com">Eko Prasetio</a>.</strong> All rights reserved.
  </footer>

app/views/base/_header.html.erb
<!-- Navbar -->
  <nav class="main-header navbar navbar-expand navbar-white navbar-light">
    <!-- Left navbar links -->
    <ul class="navbar-nav">
      <li class="nav-item">
        <a class="nav-link" data-widget="pushmenu" href="#" role="button"><i class="fas fa-bars"></i></a>
      </li>
      <li class="nav-item d-none d-sm-inline-block">
        <a href="index3.html" class="nav-link">Home</a>
      </li>
      <li class="nav-item d-none d-sm-inline-block">
          <% if current_user %>
              <%= button_to "logout", destroy_user_session_path, method: :delete, data: {turbo_method: :delete}, class: "nav-link" %>
          <% else %>
              <%= link_to "login", new_user_session_path, class: "nav-link" %>
          <% end %>
      </li>
    </ul>
  </nav>
  <!-- /.navbar -->

app/views/base/_messages.html.erb
<% flash.each do |name, msg| %>  
<div class="alert alert-success" role="alert">
   <%= msg %>
</div>
<% end %>

app/views/base/_sidebar.html.erb
  <!-- Main Sidebar Container -->
  <aside class="main-sidebar sidebar-dark-primary elevation-4">
    <!-- Brand Logo -->
    <a href="index3.html" class="brand-link">
      <img src="<%= asset_path('img/AdminLTELogo.png') %>" alt="AdminLTE Logo" class="brand-image img-circle elevation-3" style="opacity: .8">      
      <span class="brand-text font-weight-light">Technical RoR</span>
    </a>

    <!-- Sidebar -->
    <div class="sidebar">
      <!-- Sidebar user panel (optional) -->
      <div class="user-panel mt-3 pb-3 mb-3 d-flex">
        <div class="image">
          <img src="<%= asset_path('img/user2-160x160.jpg') %>" class="img-circle elevation-2" alt="User Image">
        </div>
        <div class="info">
          <a href="#" class="d-block">EKO PRASETIO</a>
        </div>
      </div>

      <!-- Sidebar Menu -->
      <nav class="mt-2">
        <ul class="nav nav-pills nav-sidebar flex-column" data-widget="treeview" role="menu" data-accordion="false">
          <!-- Add icons to the links using the .nav-icon class
               with font-awesome or any other icon font library -->
          <li class="nav-item menu-open">
            <a href="#" class="nav-link active">
              <i class="nav-icon far fa-light fa-window-restore"></i>
              <p>
                Book Management
                <i class="right fas fa-angle-left"></i>
              </p>
            </a>
            <ul class="nav nav-treeview">
            <% if current_user&.admin?%>
              <li class="nav-item">
                <%= link_to "Add Book", new_book_path(@book),  class: "nav-link far" %>
              </li>              
             <% end %>              
              <li class="nav-item">
                <%= link_to "List Book", books_path,  class: "nav-link far" %>
              </li> 
            </ul>
          </li>
          <li class="nav-item menu-open">
            <a href="#" class="nav-link active">
              <i class="nav-icon fas fa-duotone fa-user-secret"></i>
              <p>
                Author Management
                <i class="right fas fa-angle-left"></i>
              </p>
            </a>
            <ul class="nav nav-treeview">
              <li class="nav-item">
                <%= link_to "List Author", authors_path,  class: "nav-link far" %>
              </li>              
            </ul>
          </li>
          <li class="nav-item menu-open">
            <a href="#" class="nav-link active">
              <i class="nav-icon fas fa-duotone fa-user-secret"></i>
              <p>
                User Management
                <i class="right fas fa-angle-left"></i>
              </p>
            </a>
            <ul class="nav nav-treeview">    
             <% if current_user&.admin?%>        
              <li class="nav-item">
                <%= link_to "Add User", new_user_path(@book),  class: "nav-link far" %>
              </li>    
              <% end%>    
              <li class="nav-item">
                <%= link_to "List User", users_path,  class: "nav-link far" %>
              </li>              
            </ul>
          </li>
        </ul>
      </nav>
      <!-- /.sidebar-menu -->
    </div>
    <!-- /.sidebar -->
  </aside>

app/views/books/_form.html.erb
<% if @book.errors.any? %>
  <div class="alert alert-danger" role="alert">
    <ul>
      <% @book.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>
<div class="card card-primary">
    <div class="card-header">
    <h3 class="card-title">Add Book</h3>
    </div>
    <!-- /.card-header -->
    <!-- form start -->
    <%= form_with(model: @book, local: true) do |form| %>
    <div class="card-body">
        <div class="form-group">
        <label>Judul</label>
        <%= form.text_field :judul ,class:"form-control", placeholder: "Judul Buku" %>
        </div>
        <div class="form-group">
        <label>Tahun Terbit</label>
        <%= form.date_field :tahun_terbit, class:"form-control col-md-2", placeholder: "Tahun Terbit" %>
        </div>
        <div class="form-group">
        <label>Email</label>
        <%= form.text_field :email, class:"form-control col-md-2", placeholder: "Email", type: "email" %>
        </div>
        <div class="form-group">
        <label>Author</label>
        <%= form.collection_select(:author_id, Author.all, :id, :name, { prompt: 'Select an author' }, {class: "form-control select2"}) %>    
    </div>       
    </div>
    <!-- /.card-body -->

    <div class="card-footer">
        <%= form.submit "Submit", class:"btn btn-primary", type: "submit" %>
    </div>
    <% end %>
</div>

app/views/books/edit.html.erb
<%= render 'form' %>

app/views/books/index.html.erb
<div class="card">
    <div class="card-header">
    <h3 class="card-title">List Books</h3>
    </div>
    <!-- /.card-header -->
    <div class="card-body">
    <table class="table table-bordered">
        <thead>
        <tr>
            <th style="width: 10px">No</th>
            <th>Judul Buku</th>
            <th>Tahun Terbit</th>
            <th>Email</th>
            <th>Author</th>
            <th>Action</th>
        </tr>
        </thead>
        <tbody>
      <% @books.includes(:author).all.each_with_index do |book, index| %>
        <tr>
            <td><%= index + 1 %> </td>
            <td><%= book.judul %> </td>
            <td><%= book.tahun_terbit.strftime("%B %d, %Y") %> </td>
            <td><%= book.email %></td>
            <td><%= book.author.name %></td>
            <td>
                <%= link_to "", "books/#{book.id}", class: "btn btn-primary far fa-eye" %>    
                 <% if current_user&.admin?%>
                <%= link_to "", edit_book_path(book), class: "btn btn-success fas fa-edit" %>           
                <%= link_to "", "book/#{book.id}/delete", method: :delete, class: "btn btn-danger far fa-trash-alt"%> 
                <% end %>
            </td>
        </tr>        
    <% end %>
        </tbody>
    </table>
    </div>
    <!-- /.card-body -->
    <div class="card-footer clearfix">
    <ul class="pagination pagination-sm m-0 float-right">
        <%= paginate @books %>      
    </ul>
    </div>
</div>
<!-- /.card -->

app/views/books/new.html.erb
<%= render 'form' %>

app/views/books/show.html.erb
<div>
<div class="card">
    <div class="card-header">
    <h3 class="card-title">
        <i class="fas fa-text-width"></i>
        Detail 
    </h3>
    </div>
    <!-- /.card-header -->
    <div class="card-body">
    <dl class="row">
        <dt class="col-sm-4">Judul Buku</dt>
        <dd class="col-sm-8"><%= @book.judul %> </dd>
        <dt class="col-sm-4">Tahun Terbit</dt>
        <dd class="col-sm-8"><%= @book.tahun_terbit.strftime("%B %d, %Y") %> </dd>       
        <dt class="col-sm-4">Email</dt>
        <dd class="col-sm-8"><%= @book.email %> </dd>
        <dt class="col-sm-4">Author</dt>
        <dd class="col-sm-8"><%= @book.author.name %> </dd>
    </dl>
    </div>
    <!-- /.card-body -->
</div>
    <%= link_to "back", books_path, class: "btn btn-success fas fa-back" %>   
<!-- /.card -->
</div>

app/views/layouts/admin.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Pretest</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,400i,700&display=fallback">
    <%= stylesheet_link_tag "https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,400i,700&display=fallback", "data-turbo-track": "reload" %>
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= stylesheet_link_tag "adminlte", "data-turbo-track": "reload" %>
    <%= stylesheet_link_tag "all", "data-turbo-track": "reload" %>
    <%= stylesheet_link_tag "select2.min", "data-turbo-track": "reload" %>
  </head>
  <body class="hold-transition sidebar-mini">
    <div class="wrapper">
      <%= render "base/header" %>
      <%= render "base/sidebar" %>
      <!-- Content Wrapper. Contains page content -->
        <div class="content-wrapper">
          <!-- Content Header (Page header) -->
          <div class="content-header">
            <div class="container-fluid">
              <div class="row mb-2">
                <div class="col-sm-6">
                  <h1 class="m-0">Starter Page</h1>
                </div><!-- /.col -->
                <div class="col-sm-6">
                  <ol class="breadcrumb float-sm-right">
                    <li class="breadcrumb-item"><a href="#">Home</a></li>
                    <li class="breadcrumb-item active">Starter Page</li>
                  </ol>
                </div><!-- /.col -->
              </div><!-- /.row -->
            </div><!-- /.container-fluid -->
          </div>
          <!-- /.content-header -->

          <!-- Main content -->
          <div class="content">
            <div class="container-fluid">   
              <%= render "base/messages" %>
              <%= yield %>
            </div><!-- /.container-fluid -->
          </div>
          <!-- /.content -->
        </div>
        <!-- /.content-wrapper -->
    </div>
    <%= render "base/footer" %>
    <%= render "base/control_sidebar" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", defer: true %>
    <%= javascript_include_tag "jquery", "data-turbo-track": "reload", defer: true %>
    <%= javascript_include_tag "adminlte", "data-turbo-track": "reload", defer: true %>
  </body>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Pretest</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,400i,700&display=fallback">
    <%= stylesheet_link_tag "https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,400i,700&display=fallback", "data-turbo-track": "reload" %>
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= stylesheet_link_tag "adminlte", "data-turbo-track": "reload" %>
    <%= stylesheet_link_tag "all", "data-turbo-track": "reload" %>
    <%= stylesheet_link_tag "select2.min", "data-turbo-track": "reload" %>
  </head>
  <body class="hold-transition sidebar-mini">
    <div class="wrapper">
      <%= render "base/header" %>
      <%= render "base/sidebar" %>
      <!-- Content Wrapper. Contains page content -->
        <div class="content-wrapper">
          <!-- Content Header (Page header) -->
          <div class="content-header">
            <div class="container-fluid">
              <div class="row mb-2">
                <div class="col-sm-6">
                  <h1 class="m-0">Starter Page</h1>
                </div><!-- /.col -->
                <div class="col-sm-6">
                  <ol class="breadcrumb float-sm-right">
                    <li class="breadcrumb-item"><a href="#">Home</a></li>
                    <li class="breadcrumb-item active">Starter Page</li>
                  </ol>
                </div><!-- /.col -->
              </div><!-- /.row -->
            </div><!-- /.container-fluid -->
          </div>
          <!-- /.content-header -->

          <!-- Main content -->
          <div class="content">
            <div class="container-fluid">   
              <%= render "base/messages" %>
              <%= yield %>
            </div><!-- /.container-fluid -->
          </div>
          <!-- /.content -->
        </div>
        <!-- /.content-wrapper -->
    </div>
    <%= render "base/footer" %>
    <%= render "base/control_sidebar" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", defer: true %>
    <%= javascript_include_tag "jquery", "data-turbo-track": "reload", defer: true %>
    <%= javascript_include_tag "adminlte", "data-turbo-track": "reload", defer: true %>
  </body>
</html>

app/views/layouts/frontend.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Blog</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,400i,700&display=fallback">
    <%= stylesheet_link_tag "https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,400i,700&display=fallback", "data-turbo-track": "reload" %>
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= stylesheet_link_tag "adminlte", "data-turbo-track": "reload" %>
    <%= stylesheet_link_tag "all", "data-turbo-track": "reload" %>
  </head>
  <body class="hold-transition login-page">
    <div class="login-box">
    <div class="login-logo">
        <a href="../../index2.html"><b>PRETEST</b>ROR</a>
    </div>
    <!-- /.login-logo -->
    <div class="card">
        <div class="card-body login-card-body">
        <p class="login-box-msg">Sign in to start your session</p>
        <%= form_for(resource, as: resource_name, url: session_path(resource_name)) do |f| %>
            <div class="input-group mb-3">
            <%= f.email_field :email, autofocu: true, autocomplete: "email", placeholder: "Email", type: "email", class: "form-control" %>
            <div class="input-group-append">
                <div class="input-group-text">
                <span class="fas fa-envelope"></span>
                </div>
            </div>
            </div>
            <div class="input-group mb-3">
            <%= f.password_field :password, autocomplete: "current-password", class: "form-control", placeholder: "Password", type: "password" %>
            <div class="input-group-append">
                <div class="input-group-text">
                <span class="fas fa-lock"></span>
                </div>
            </div>
            </div>
            <div class="row">
            <% if devise_mapping.rememberable?%>
            <div class="col-8">
                <div class="icheck-primary">
                <%= f.check_box :remember_me, type: "checkbox" %>
                <label for="remember">
                    Remember Me
                </label>
                </div>
            </div>
            <% end %>
            <!-- /.col -->
            <div class="col-4">
                <%= f.submit "Log in", disable_with: 'Log ining...', class: "btn btn-primary btn-block", type: "submit" %>
            </div>
            <!-- /.col -->
            </div>
        </form>
        <% end %>

        <div class="social-auth-links text-center mb-3">
            <p>- OR -</p>            
        </div>
        <!-- /.social-auth-links -->
        <p class="mb-0">
            <%= link_to "Register a new membership", users_path,  class: "text-center" %>
        </p>
        </div>
        <!-- /.login-card-body -->
    </div>
    </div>
    <!-- /.login-box -->
    <%= javascript_include_tag "application", "data-turbo-track": "reload", defer: true %>
    <%= javascript_include_tag "jquery", "data-turbo-track": "reload", defer: true %>
    <%= javascript_include_tag "adminlte", "data-turbo-track": "reload", defer: true %>
  </body>
</html>

app/views/layouts/user.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Pretest</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,400i,700&display=fallback">
    <%= stylesheet_link_tag "https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,400i,700&display=fallback", "data-turbo-track": "reload" %>
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= stylesheet_link_tag "adminlte", "data-turbo-track": "reload" %>
    <%= stylesheet_link_tag "all", "data-turbo-track": "reload" %>
    <%= stylesheet_link_tag "select2.min", "data-turbo-track": "reload" %>
  </head>
  <body class="hold-transition sidebar-mini">
    <div class="wrapper">
      <%= render "base/header" %>
      <%= render "base/sidebar" %>
      <!-- Content Wrapper. Contains page content -->
        <div class="content-wrapper">
          <!-- Content Header (Page header) -->
          <div class="content-header">
            <div class="container-fluid">
              <div class="row mb-2">
                <div class="col-sm-6">
                  <h1 class="m-0">Starter Page</h1>
                </div><!-- /.col -->
                <div class="col-sm-6">
                  <ol class="breadcrumb float-sm-right">
                    <li class="breadcrumb-item"><a href="#">Home</a></li>
                    <li class="breadcrumb-item active">Starter Page</li>
                  </ol>
                </div><!-- /.col -->
              </div><!-- /.row -->
            </div><!-- /.container-fluid -->
          </div>
          <!-- /.content-header -->

          <!-- Main content -->
          <div class="content">
            <div class="container-fluid">   
              <%= render "base/messages" %>
              <%= yield %>
            </div><!-- /.container-fluid -->
          </div>
          <!-- /.content -->
        </div>
        <!-- /.content-wrapper -->
    </div>
    <%= render "base/footer" %>
    <%= render "base/control_sidebar" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", defer: true %>
    <%= javascript_include_tag "jquery", "data-turbo-track": "reload", defer: true %>
    <%= javascript_include_tag "adminlte", "data-turbo-track": "reload", defer: true %>
  </body>
</html>

app/views/pages/home.html.erb
<% if current_user %>
<%= current_user.role %>
<%= link_to "logout", destroy_user_session_path, method: :delete, data: {turbo_method: :delete} %>
<% else %>
<%= link_to "login", new_user_session_path %>
<% end %> 


<h1>Welcome to Mini Project </h1>
<h3>Instructions</h3>
<h4>. Click Create Book and Fill out the form;</h4>
<h4>. Enter a VALID EMAIL ADDRESS, please;</h4>
<%= button_to("Create Book", new_book_path,   method: :get,  class:"btn btn-primary") %>

app/views/users/_form.html.erb
<% if @user.errors.any? %>
  <div class="alert alert-danger" role="alert">
    <ul>
      <% @user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>
<div class="card card-primary">
    <div class="card-header">
    <h3 class="card-title">Add User</h3>
    </div>
    <!-- /.card-header -->
    <!-- form start -->
    <%= form_with(model: @user, local: true) do |form| %>
    <div class="card-body">
        <div class="form-group">
        <label>Username</label>
        <%= form.text_field :username ,class:"form-control col-md-2", placeholder: "Username" %>
        </div>
        <div class="form-group">
        <label>Email</label>
        <%= form.text_field :email, class:"form-control col-md-2", placeholder: "Email", type: "email" %>
        </div>  
        <div class="form-group">
        <label>Password</label>
        <% if @minimum_password_length %>
        <em>(<%= @minimum_password_length %> characters minimum)</em>
        <% end %><br />
        <%= form.password_field :password, class:"form-control col-md-2", placeholder: "Password", type: "password" %>
        </div>  
        <div class="form-group">        
        <label>Password Confirmation</label>
        <%= form.password_field :password_confirmation, class:"form-control col-md-2", placeholder: "Password Confirmation", type: "password" %>
        </div>  

    </div>
    <!-- /.card-body -->

    <div class="card-footer">
        <%= form.submit "Submit", class:"btn btn-primary", type: "submit" %>
    </div>
    <% end %>
</div>

app/views/users/index.html.erb
<div class="card">
    <div class="card-header">
    <h3 class="card-title">List Users</h3>
    </div>
    <!-- /.card-header -->
    <div class="card-body">
    <table class="table table-bordered">
        <thead>
        <tr>
            <th style="width: 10px">No</th>
            <th>Email</th>  
            <th>Username</th>  
        </tr>
        </thead>
        <tbody>
      <% @users.each_with_index do |user, index| %>
        <tr>
            <td><%= index + 1 %> </td>
            <td><%= user.email %> </td>  
            <td><%= user.username %> </td>  
        </tr>        
    <% end %>
        </tbody>
    </table>
    </div>
    <!-- /.card-body -->
    <div class="card-footer clearfix">
    <ul class="pagination pagination-sm m-0 float-right">
        <%= paginate @users %>      
    </ul>
    </div>
</div>
<!-- /.card -->

app/views/users/new.html.erb
<%= render 'form' %>